# mdm/nix-modules/mdm.nix
# Home Manager module for a local NanoMDM server that installs the profiles
# generated by `programs.macprofile` automatically, instead of requiring the
# user to double-click a `.mobileconfig`.
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.macprofile.mdm;

  # NanoMDM reads its API key from the NANOMDM_API environment variable. It is
  # deliberately never passed as an argv element (`ps` exposes argv to every
  # local user) and never written into the launchd plist either: Home Manager
  # writes agent plists into ~/Library/LaunchAgents with world-readable
  # permissions, so `EnvironmentVariables` there would leak the key just as
  # badly. The wrapper reads the file at start time instead, which also keeps
  # the key out of the world-readable Nix store.
  #
  # `-checkin` makes NanoMDM serve the check-in protocol on a separate
  # `/checkin` endpoint rather than multiplexing it onto `/mdm`. That is why
  # the enrollment profile generated by `nixmagic-mdm` must set `CheckInURL`
  # in addition to `ServerURL`.
  # Every interpolated path goes through `escapeShellArg`. A home directory
  # containing a space would otherwise split `-ca /Users/jane doe/...` into two
  # argv elements, NanoMDM would fatal on the stray argument, and
  # `KeepAlive = true` would turn that into a restart loop.
  nanomdmWrapper = pkgs.writeShellScript "nanomdm-wrapper" ''
    set -euo pipefail

    apiKeyFile=${escapeShellArg cfg.apiKeyFile}

    if [ ! -r "$apiKeyFile" ]; then
      echo "nanomdm: API key file $apiKeyFile is missing or unreadable" >&2
      exit 1
    fi

    mkdir -p ${escapeShellArg "${cfg.stateDir}/db"} ${escapeShellArg "${cfg.stateDir}/log"}

    NANOMDM_API="$(cat "$apiKeyFile")"
    export NANOMDM_API

    exec ${cfg.package}/bin/nanomdm \
      -listen ${escapeShellArg cfg.listen} \
      -ca ${escapeShellArg "${cfg.stateDir}/ca/ca.pem"} \
      -storage filekv -storage-dsn ${escapeShellArg "${cfg.stateDir}/db"} \
      -checkin${optionalString cfg.debug " \\\n  -debug"}
  '';

  # The CLI on PATH must carry the module's settings, otherwise a non-default
  # `stateDir`, `hostname` or `tlsPort` silently breaks every manual
  # invocation while the activation hook (which passes the flags explicitly)
  # keeps working. `cliPackage` itself stays unwrapped so the option default
  # remains a plain package; the wrapping happens here, at the point of use.
  wrappedCli = pkgs.symlinkJoin {
    name = "nixmagic-mdm-configured";
    paths = [ cfg.cliPackage ];
    nativeBuildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram "$out/bin/nixmagic-mdm" \
        --add-flags "--state-dir ${escapeShellArg cfg.stateDir}" \
        --add-flags "--server-url ${escapeShellArg cfg.serverUrl}" \
        --add-flags "--api-key-file ${escapeShellArg cfg.apiKeyFile}"
    '';
  };

  # Caddy terminates TLS in front of NanoMDM's plaintext loopback listener,
  # because the MDM client refuses plain HTTP.
  #
  # `skip_install_trust`: Caddy would otherwise install its internal root into
  # the system trust store, which prompts for sudo on every start. The root is
  # instead handed to the device inside the enrollment profile as a
  # `com.apple.security.root` payload, which is the only trust anchor the MDM
  # client needs.
  #
  # `admin off`: Caddy's admin API is not used here, and binding it would add
  # a local control socket that can reconfigure the server — unnecessary local
  # attack surface.
  #
  # `storage file { root ... }`: Caddy keeps its internal PKI *inside storage*,
  # at `<storage root>/pki/authorities/<ca id>/root.crt`. Setting the storage
  # root here is what makes the root certificate land exactly at `caRootPath`.
  # It also fully replaces the default storage location, so the environment
  # variables that select that default (XDG_DATA_HOME, HOME) have no effect
  # once this block is present — which is why the launchd agent sets none.
  caddyfile = pkgs.writeText "Caddyfile" ''
    {
    	admin off
    	skip_install_trust
    	local_certs
    	storage file {
    		root "${cfg.stateDir}/caddy"
    	}
    	pki {
    		ca local {
    			name "nixmagic MDM local CA"
    		}
    	}
    }

    https://${cfg.hostname}:${toString cfg.tlsPort} {
    	tls internal
    	reverse_proxy ${cfg.listen}
    }
  '';

  # The launchd agents are darwin-only. `launchd.agents` *is* declared on
  # Linux by Home Manager (modules/launchd/default.nix is imported
  # unconditionally), so a plain `mkIf` is sufficient: the option exists, and
  # on Linux the definition is discarded before Home Manager's
  # "Must use Darwin for modules that require Launchd" assertion looks at the
  # agent set. No `optionalAttrs` gymnastics needed.
  launchdAgents = {
    nanomdm = {
      enable = true;
      config = {
        ProgramArguments = [ "${nanomdmWrapper}" ];
        RunAtLoad = true;
        KeepAlive = true;
        StandardOutPath = "${cfg.stateDir}/log/nanomdm.log";
        StandardErrorPath = "${cfg.stateDir}/log/nanomdm.err.log";
      };
    };
  } // optionalAttrs cfg.caddy.enable {
    nanomdm-caddy = {
      enable = true;
      config = {
        ProgramArguments = [
          "${cfg.caddy.package}/bin/caddy"
          "run"
          "--config"
          "${caddyfile}"
          "--adapter"
          "caddyfile"
        ];
        RunAtLoad = true;
        KeepAlive = true;
        StandardOutPath = "${cfg.stateDir}/log/caddy.log";
        StandardErrorPath = "${cfg.stateDir}/log/caddy.err.log";
        # No EnvironmentVariables: the Caddyfile's `storage file { root ... }`
        # already pins the data location, and launchd agent plists are written
        # world-readable into ~/Library/LaunchAgents, so this block must stay
        # free of anything sensitive.
      };
    };
  };

  # Directories the server and the CLI expect to exist before first start.
  stateSubdirs = [ "ca" "device" "push" "db" "log" "caddy" ];

in
{
  # This module reads `config.programs.macprofile.enable` and `.outputPaths`,
  # so it cannot evaluate on its own: imported standalone it fails with
  # "attribute 'enable' missing". Importing the core module is preferred over
  # guarding every read with `config.programs.macprofile ? enable`, because a
  # guard would silently turn the "requires macprofile.enable" assertion and
  # the user-scope warning into no-ops. This costs nothing in
  # `homeModules.default`, which also lists the core module: the module system
  # keys modules by their file path and evaluates each path exactly once, so
  # the repeated import is deduplicated rather than merged twice.
  imports = [ ../../nix-modules/generateMacOSProfile.nix ];

  options.programs.macprofile.mdm = {
    enable = mkEnableOption
      "a local NanoMDM server that installs generated profiles automatically";

    package = mkOption {
      type = types.package;
      default = pkgs.callPackage ../packages/nanomdm.nix { };
      defaultText = literalExpression "pkgs.callPackage ../packages/nanomdm.nix { }";
      description = "The NanoMDM package providing `bin/nanomdm`.";
    };

    cliPackage = mkOption {
      type = types.package;
      default = pkgs.callPackage ../packages/nixmagic-mdm.nix { };
      defaultText = literalExpression "pkgs.callPackage ../packages/nixmagic-mdm.nix { }";
      description = ''
        The package providing `bin/nixmagic-mdm`, the helper CLI used for the
        one-time certificate and enrollment setup and for pushing profiles.
      '';
    };

    listen = mkOption {
      type = types.str;
      default = "127.0.0.1:9000";
      description = ''
        Address NanoMDM's plaintext HTTP listener binds to.

        This must stay on loopback: the listener speaks unencrypted HTTP and
        carries the API key in request headers. TLS for the device-facing
        endpoint is terminated by Caddy in front of it.
      '';
    };

    hostname = mkOption {
      type = types.str;
      default = "localhost";
      description = ''
        Host name the device uses to reach the MDM server. It must match the
        name in the TLS certificate Caddy issues, and appears in the
        `ServerURL` of the enrollment profile.
      '';
    };

    tlsPort = mkOption {
      type = types.port;
      default = 9443;
      description = "Port for Caddy's HTTPS listener, i.e. the port the device connects to.";
    };

    stateDir = mkOption {
      type = types.str;
      default = "${config.home.homeDirectory}/.local/state/nixmagic-mdm";
      defaultText = literalExpression ''"''${config.home.homeDirectory}/.local/state/nixmagic-mdm"'';
      description = ''
        Directory holding all MDM runtime state: the CA, the APNs push
        certificate, the device database, logs, and Caddy's internal PKI.

        It is created outside the Nix store on purpose, since it contains
        private keys and must not be world-readable.
      '';
    };

    apiKeyFile = mkOption {
      type = types.str;
      default = "${cfg.stateDir}/api.key";
      defaultText = literalExpression ''"''${stateDir}/api.key"'';
      example = "/Users/me/.config/nixmagic-mdm/api-key";
      description = ''
        Path to the file containing NanoMDM's API key.

        The default is the path `nixmagic-mdm init` generates the key at and
        the path the CLI reads it from, so server and client cannot end up
        authenticating with different keys. When this is pointed elsewhere the
        CLI is told about it too: both the `nixmagic-mdm` on `PATH` and the
        push hook pass `--api-key-file`.

        The key is read from this file at service start time rather than being
        written into the configuration, so it never enters the world-readable
        Nix store, never appears in the process arguments, and never lands in
        the launchd plist.
      '';
    };

    enrollmentId = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Enrollment ID of the device channel to push to, i.e. the hardware UDID
        of the enrolled Mac.

        When null the CLI autodiscovers the enrollment from NanoMDM's device
        database, which is the usual case for a single self-managed machine.
      '';
    };

    enrollmentIdFile = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Path to a file containing the device-channel enrollment ID, for cases
        where the ID should not be written into the configuration.
      '';
    };

    userEnrollmentId = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "00000000-0000-0000-0000-000000000000:11111111-1111-1111-1111-111111111111";
      description = ''
        Enrollment ID of the *user* channel, in `UUID:UUID` form (device UDID
        followed by the user's identifier).

        Only user-channel enrollments can install user-scope profiles. MDM
        normally delivers profiles on the device channel, so this is left null
        unless a User-scope profile actually needs to be pushed.
      '';
    };

    pushOnChange = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Whether the generated profiles should be pushed to the device when
        they change, rather than only on an explicit `nixmagic-mdm push`.
      '';
    };

    caddy = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = ''
          Whether to run Caddy as the TLS front end for NanoMDM.

          Disable this only when another reverse proxy already terminates TLS
          for `serverUrl`; the MDM client will not talk plain HTTP.
        '';
      };

      package = mkOption {
        type = types.package;
        default = pkgs.caddy;
        defaultText = literalExpression "pkgs.caddy";
        description = "The Caddy package used for TLS termination.";
      };
    };

    debug = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to run NanoMDM with `-debug`, which logs full protocol traffic.";
    };

    serverUrl = mkOption {
      type = types.str;
      readOnly = true;
      default = "https://${cfg.hostname}:${toString cfg.tlsPort}";
      defaultText = literalExpression ''"https://''${hostname}:''${toString tlsPort}"'';
      description = ''
        Resolved base URL of the MDM server. Exposed read-only so the push hook
        and the enrollment profile agree on one value.
      '';
    };

    caRootPath = mkOption {
      type = types.str;
      readOnly = true;
      default = "${cfg.stateDir}/caddy/pki/authorities/local/root.crt";
      defaultText = literalExpression ''"''${stateDir}/caddy/pki/authorities/local/root.crt"'';
      description = ''
        Path to the root certificate of Caddy's internal CA. Since the root is
        never added to the system trust store, the CLI passes this file as
        `--cacert` when it talks to `serverUrl`.
      '';
    };

    # Store paths of the generated service inputs, exposed so the test suite
    # can assert on their contents without rebuilding them.
    _wrapperScript = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      default = nanomdmWrapper;
      defaultText = literalExpression "<generated nanomdm wrapper script>";
      description = "Store path of the generated NanoMDM wrapper script.";
    };

    _caddyfile = mkOption {
      type = types.path;
      internal = true;
      readOnly = true;
      default = caddyfile;
      defaultText = literalExpression "<generated Caddyfile>";
      description = "Store path of the generated Caddyfile.";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    # Assertions, warnings and the CLI must evaluate on every platform: the
    # test suite runs `nix flake check` on Linux and needs to exercise them.
    {
      # There is deliberately no "apiKeyFile must be set" assertion any more:
      # the option now always has a value (it defaults to the path the CLI
      # generates the key at), so such an assertion could never fire.
      assertions = [
        {
          assertion = config.programs.macprofile.enable;
          message = ''
            programs.macprofile.mdm.enable requires
            programs.macprofile.enable.

            The MDM server exists to install the configuration profiles that
            programs.macprofile generates; with profile generation disabled
            there is nothing to push, so enabling the server alone has no
            effect.
          '';
        }
      ];

      warnings = optional
        (cfg.userEnrollmentId == null
          && config.programs.macprofile.outputPaths ? User)
        ''
          programs.macprofile generates a User-scope profile, but
          programs.macprofile.mdm.userEnrollmentId is null, so that profile
          will not be pushed: user-scope profiles can only be installed over
          the user channel.

          MDM normally delivers profiles on the device channel. Either move
          the affected payloads to the System scope, or set userEnrollmentId
          to the `UUID:UUID` identifier of the enrolled user channel.
        '';

      home.packages = [ wrappedCli ];

      # `pushOnChange` is consumed by the CLI's push hook; the state directory
      # only has to exist before either the agents or the CLI run.
      home.activation.mdmStateDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if [[ "$OSTYPE" == "darwin"* ]]; then
          $DRY_RUN_CMD mkdir -p ${escapeShellArg cfg.stateDir}
          $DRY_RUN_CMD chmod 0700 ${escapeShellArg cfg.stateDir}
          ${concatMapStringsSep "\n  " (d: ''
            $DRY_RUN_CMD mkdir -p ${escapeShellArg "${cfg.stateDir}/${d}"}'')
            stateSubdirs}

          # The setup flow needs human steps at Apple's web portals (signing
          # the push CSR, downloading the APNs certificate), so nothing here
          # runs the CLI on the user's behalf.
          if [[ ! -f ${escapeShellArg "${cfg.stateDir}/enrollment.mobileconfig"} ]]; then
            $DRY_RUN_CMD echo "nixmagic-mdm: no enrollment profile yet; run 'nixmagic-mdm csr' to start setup"
          fi
        fi
      '';
    }

    (mkIf pkgs.stdenv.hostPlatform.isDarwin {
      launchd.agents = launchdAgents;
    })
  ]);
}
